-- ============================================================
--  SmartParkingDB — Migration v3
--  Adds: ExtensionRequests table + EBike vehicle/slot type.
--  Idempotent — safe to re-run.
-- ============================================================

USE SmartParkingDB;
GO

-- ────────────────────────────────────────────────────────────
--  1. Expand CHECK constraints to include 'EBike'
--     Constraint names are auto-generated by SQL Server, so we
--     look them up in sys.check_constraints and drop dynamically.
-- ────────────────────────────────────────────────────────────

-- Vehicles.VehicleType
DECLARE @cn NVARCHAR(200);
SELECT @cn = name
FROM   sys.check_constraints
WHERE  parent_object_id = OBJECT_ID('Vehicles')
  AND  definition LIKE '%VehicleType%';
IF @cn IS NOT NULL EXEC('ALTER TABLE Vehicles DROP CONSTRAINT ' + @cn);
ALTER TABLE Vehicles
    ADD CONSTRAINT CHK_Vehicle_Type
    CHECK (VehicleType IN ('Car', 'Bike', 'EBike', 'EV'));
GO

-- ParkingSlots.SlotType
DECLARE @cn NVARCHAR(200);
SELECT @cn = name
FROM   sys.check_constraints
WHERE  parent_object_id = OBJECT_ID('ParkingSlots')
  AND  definition LIKE '%SlotType%';
IF @cn IS NOT NULL EXEC('ALTER TABLE ParkingSlots DROP CONSTRAINT ' + @cn);
ALTER TABLE ParkingSlots
    ADD CONSTRAINT CHK_ParkingSlot_Type
    CHECK (SlotType IN ('Car', 'Bike', 'EBike', 'EV'));
GO

-- PricingRules.SlotType
DECLARE @cn NVARCHAR(200);
SELECT @cn = name
FROM   sys.check_constraints
WHERE  parent_object_id = OBJECT_ID('PricingRules')
  AND  definition LIKE '%SlotType%';
IF @cn IS NOT NULL EXEC('ALTER TABLE PricingRules DROP CONSTRAINT ' + @cn);
ALTER TABLE PricingRules
    ADD CONSTRAINT CHK_PricingRule_Type
    CHECK (SlotType IN ('Car', 'Bike', 'EBike', 'EV'));
GO

-- Seed an EBike pricing rule if none exists
IF NOT EXISTS (SELECT 1 FROM PricingRules WHERE SlotType = 'EBike')
    INSERT INTO PricingRules (SlotType, PricePerHour, EffectiveFrom)
    VALUES ('EBike', 70.00, CAST(GETDATE() AS DATE));
GO

-- ────────────────────────────────────────────────────────────
--  2. ExtensionRequests table
-- ────────────────────────────────────────────────────────────
IF OBJECT_ID('ExtensionRequests', 'U') IS NULL
BEGIN
    CREATE TABLE ExtensionRequests (
        ExtensionRequestID INT          IDENTITY(1,1) PRIMARY KEY,
        ReservationID      INT          NOT NULL,
        RequestedEndTime   DATETIME     NOT NULL,
        UserNote           VARCHAR(200) NULL,
        Status             VARCHAR(20)  NOT NULL DEFAULT 'Pending'
                           CHECK (Status IN ('Pending', 'Approved', 'Denied')),
        AdminNote          VARCHAR(200) NULL,
        CreatedAt          DATETIME     NOT NULL DEFAULT GETDATE(),
        ResolvedAt         DATETIME     NULL,
        ResolvedBy         INT          NULL,

        CONSTRAINT FK_Extension_Reservation
            FOREIGN KEY (ReservationID) REFERENCES Reservations(ReservationID)
            ON DELETE CASCADE,
        CONSTRAINT FK_Extension_ResolvedBy
            FOREIGN KEY (ResolvedBy) REFERENCES Users(UserID)
    );

    CREATE INDEX IX_Extension_Status ON ExtensionRequests(Status);
    CREATE INDEX IX_Extension_Reservation ON ExtensionRequests(ReservationID);
END
GO

-- ────────────────────────────────────────────────────────────
--  3. View: ExtensionRequestDetails
-- ────────────────────────────────────────────────────────────
IF OBJECT_ID('ExtensionRequestDetails', 'V') IS NOT NULL
    DROP VIEW ExtensionRequestDetails;
GO
CREATE VIEW ExtensionRequestDetails AS
SELECT  er.ExtensionRequestID,
        er.ReservationID,
        er.RequestedEndTime,
        er.UserNote,
        er.Status,
        er.AdminNote,
        er.CreatedAt,
        er.ResolvedAt,
        er.ResolvedBy,
        r.UserID,
        r.StartTime    AS ReservationStart,
        r.EndTime      AS ReservationEnd,
        r.ReservationStatus,
        r.CheckInTime,
        u.FullName     AS UserName,
        u.Email        AS UserEmail,
        s.SlotID,
        s.SlotNumber,
        s.SlotLocation,
        s.SlotType
FROM    ExtensionRequests er
JOIN    Reservations  r ON er.ReservationID = r.ReservationID
JOIN    Users         u ON r.UserID         = u.UserID
JOIN    ParkingSlots  s ON r.SlotID         = s.SlotID;
GO

-- ============================================================
--  SAMPLE QUERIES
-- ============================================================
-- SELECT * FROM ExtensionRequestDetails WHERE Status = 'Pending';
-- INSERT INTO Vehicles (UserID, LicensePlate, VehicleType) VALUES (1, 'EB-001', 'EBike');
